export const VALORES_CONSULTA = {
    "Alergología": 14000,
    "Angiología": 16000,
    "Cardiología": 18000,
    "Cirugía General": 20000,
    "Cirugía Plástica": 22000,
    "Dermatología": 15000,
    "Diabetología": 17500,
    "Endocrinología": 17000,
    "Gastroenterología": 16500,
    "Geriatría": 15500,
    "Ginecología": 16000,
    "Hematología": 18000,
    "Infectología": 17500,
    "Medicina Familiar": 14000,
    "Medicina Interna": 16000,
    "Nefrología": 18000,
    "Neumología": 17000,
    "Neurología": 19000,
    "Nutrición": 13000,
    "Obstetricia": 16000,
    "Odontología": 12000,
    "Oftalmología": 15000,
    "Oncología": 20000,
    "Otorrinolaringología": 15500,
    "Pediatría": 15000,
    "Psiquiatría": 17000,
    "Psicología": 12000,
    "Reumatología": 16500,
    "Traumatología": 17000,
    "Urología": 16000,
    "Fisiatría": 14500,
    "Fonoaudiología": 13000,
    "Neurocirugía": 22000,
    "Gastroenterología Pediátrica": 16500,
    "Cardiología Pediátrica": 18000
};

export const DESCUENTOS_OS = {
    "OSDE": 15,
    "Medifé": 10,
    "Swiss Medical": 12,
    "Omint": 8,
    "Galeno": 10,
    "Accord Salud": 7,
    "Sancor Salud": 10,
    "UP": 5,
    "PAMI": 20,
    "IOMA": 20,
    "OSDE Binario": 15,
    "Medicus": 12,
    "Asociación Española": 10,
    "OSPACA": 12,
    "OSPAT": 10,
    "OSPM": 10,
    "OMINT Premium": 12,
    "OMINT Clásica": 8,
    "Swiss Medical Group": 12,
    "Hospital Italiano": 10,
    "Cemopar": 8,
    "Obra Social del Personal de Comercio": 10,
    "Obra Social de Petroleros": 10,
    "Obra Social de Camioneros": 10,
    "Obra Social de Luz y Fuerza": 10,
    "Obra Social de Judiciales": 10,
    "Obra Social de Docentes": 10,
    "OSFATUN": 10,
    "OSSEG": 10,
    "Obra Social de Empleados de Comercio": 10,
    "OSUNL": 10,
    "OSDEPYM": 8
};

export const OBRAS_SOCIALES = [
    { id: 1, nombre: "OSDE", descripcion: "OSDE" },
    { id: 2, nombre: "Medifé", descripcion: "Medifé" },
    { id: 3, nombre: "Swiss Medical", descripcion: "Swiss Medical" },
    { id: 4, nombre: "Omint", descripcion: "Omint" },
    { id: 5, nombre: "Galeno", descripcion: "Galeno" },
    { id: 6, nombre: "Accord Salud", descripcion: "Accord Salud" },
    { id: 7, nombre: "Sancor Salud", descripcion: "Sancor Salud" },
    { id: 8, nombre: "UP", descripcion: "UP" },
    { id: 9, nombre: "PAMI", descripcion: "PAMI" },
    { id: 10, nombre: "IOMA", descripcion: "IOMA" },
    { id: 11, nombre: "OSDE Binario", descripcion: "OSDE Binario" },
    { id: 12, nombre: "Medicus", descripcion: "Medicus" },
    { id: 13, nombre: "Asociación Española", descripcion: "Asociación Española" },
    { id: 14, nombre: "OSPACA", descripcion: "OSPACA" },
    { id: 15, nombre: "OSPAT", descripcion: "OSPAT" },
    { id: 16, nombre: "OSPM", descripcion: "OSPM" },
    { id: 17, nombre: "OMINT Premium", descripcion: "OMINT Premium" },
    { id: 18, nombre: "OMINT Clásica", descripcion: "OMINT Clásica" },
    { id: 19, nombre: "Swiss Medical Group", descripcion: "Swiss Medical Group" },
    { id: 20, nombre: "Hospital Italiano", descripcion: "Hospital Italiano" },
    { id: 21, nombre: "Cemopar", descripcion: "Cemopar" },
    { id: 22, nombre: "Obra Social del Personal de Comercio", descripcion: "Obra Social del Personal de Comercio" },
    { id: 23, nombre: "Obra Social de Petroleros", descripcion: "Obra Social de Petroleros" },
    { id: 24, nombre: "Obra Social de Camioneros", descripcion: "Obra Social de Camioneros" },
    { id: 25, nombre: "Obra Social de Luz y Fuerza", descripcion: "Obra Social de Luz y Fuerza" },
    { id: 26, nombre: "Obra Social de Judiciales", descripcion: "Obra Social de Judiciales" },
    { id: 27, nombre: "Obra Social de Docentes", descripcion: "Obra Social de Docentes" },
    { id: 28, nombre: "OSFATUN", descripcion: "OSFATUN" },
    { id: 29, nombre: "OSSEG", descripcion: "OSSEG" },
    { id: 30, nombre: "Obra Social de Empleados de Comercio", descripcion: "Obra Social de Empleados de Comercio" },
    { id: 31, nombre: "OSUNL", descripcion: "OSUNL" },
    { id: 32, nombre: "OSDEPYM", descripcion: "OSDEPYM" }
];